// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using maria.Model;

#nullable disable

namespace maria.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219072257_heightWall")]
    partial class heightWall
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("maria.Model.CheckingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CheckingItems");
                });

            modelBuilder.Entity("maria.Model.CheckingItemReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckingItemId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectiveAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CorrectiveActionFlag")
                        .HasColumnType("bit");

                    b.Property<int>("SiteReportId")
                        .HasColumnType("int");

                    b.Property<string>("fault")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("faultFlag")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CheckingItemId");

                    b.HasIndex("SiteReportId");

                    b.ToTable("CheckingItemReports");
                });

            modelBuilder.Entity("maria.Model.DeliveryNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OptionalFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("UnitFlag")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DeliveryNotes");
                });

            modelBuilder.Entity("maria.Model.DeliveryNoteReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UnitValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("deliveryNoteId")
                        .HasColumnType("int");

                    b.Property<int>("deliveryReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("deliveryNoteId");

                    b.HasIndex("deliveryReportId");

                    b.ToTable("DeliveryNoteReport");
                });

            modelBuilder.Entity("maria.Model.DeliveryReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DeliveryReport");
                });

            modelBuilder.Entity("maria.Model.DelivryReportImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("deliveryReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("deliveryReportId");

                    b.ToTable("DelivryReportImages");
                });

            modelBuilder.Entity("maria.Model.Elevator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectionImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResizableImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WallStatusForList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WellImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("capinaHeight")
                        .HasColumnType("int");

                    b.Property<string>("capinaStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("centerWidth")
                        .HasColumnType("int");

                    b.Property<int>("directionHeight")
                        .HasColumnType("int");

                    b.Property<int>("directionWidth")
                        .HasColumnType("int");

                    b.Property<string>("doorDirections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doortwoDirections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("floorHeights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("floors")
                        .HasColumnType("int");

                    b.Property<int>("foundationHeight")
                        .HasColumnType("int");

                    b.Property<string>("garagsDirections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("garagsHeights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("garagsNum")
                        .HasColumnType("int");

                    b.Property<string>("garagstwoDirections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("heightShape")
                        .HasColumnType("int");

                    b.Property<int?>("liftWidth")
                        .HasColumnType("int");

                    b.Property<int?>("radiusShape")
                        .HasColumnType("int");

                    b.Property<string>("reportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("resizableSquareHeight")
                        .HasColumnType("int");

                    b.Property<int>("resizableSquarewidth")
                        .HasColumnType("int");

                    b.Property<int?>("rightWidth")
                        .HasColumnType("int");

                    b.Property<string>("salesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shapeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("twoDirectionFlag")
                        .HasColumnType("bit");

                    b.Property<string>("typeElevator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wellStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("widthShape")
                        .HasColumnType("int");

                    b.Property<string>("workRequied")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Elevator");
                });

            modelBuilder.Entity("maria.Model.ElevatorChechingItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ElevatorChechingItems");
                });

            modelBuilder.Entity("maria.Model.ElevatorImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElevatorId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorId");

                    b.ToTable("ElevatorImage");
                });

            modelBuilder.Entity("maria.Model.ElevatorInspectionImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElevatorInspectionId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorInspectionId");

                    b.ToTable("ElevatorInspectionImage");
                });

            modelBuilder.Entity("maria.Model.ElevatorInspectionItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckingItemId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectiveAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CorrectiveActionFlag")
                        .HasColumnType("bit");

                    b.Property<int>("ElevatorInspectionReportId")
                        .HasColumnType("int");

                    b.Property<string>("fault")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("faultFlag")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CheckingItemId");

                    b.HasIndex("ElevatorInspectionReportId");

                    b.ToTable("ElevatorInspectionItems");
                });

            modelBuilder.Entity("maria.Model.ElevatorInspectionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projectlocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ElevatorInspectionReport");
                });

            modelBuilder.Entity("maria.Model.Facade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("bit");

                    b.Property<int>("LevatorReportId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfFinish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfLand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfWall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("heightWall")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LevatorReportId");

                    b.ToTable("Facade");
                });

            modelBuilder.Entity("maria.Model.LevatorImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevatorReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevatorReportId");

                    b.ToTable("LevatorImage");
                });

            modelBuilder.Entity("maria.Model.LevatorReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingKind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projectlocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LevatorReport");
                });

            modelBuilder.Entity("maria.Model.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Breakdown")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSignaturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cradle")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Delivery")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Inspection")
                        .HasColumnType("int");

                    b.Property<int?>("Installation")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Meter")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelMarnia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelMarniaHireOrSale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OnScaffolding")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodicMaintenance")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Removing")
                        .HasColumnType("int");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shifting")
                        .HasColumnType("int");

                    b.Property<string>("TechName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechSignaturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThirdParty")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WarrantyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receivedPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spareParts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("maria.Model.ReportImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportFiles");
                });

            modelBuilder.Entity("maria.Model.SafetyItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SafetyItems");
                });

            modelBuilder.Entity("maria.Model.SafetyItemsReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectiveAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CorrectiveActionFlag")
                        .HasColumnType("bit");

                    b.Property<int>("SafetyItemsId")
                        .HasColumnType("int");

                    b.Property<int>("SafetyReportId")
                        .HasColumnType("int");

                    b.Property<string>("fault")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("faultFlag")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SafetyItemsId");

                    b.HasIndex("SafetyReportId");

                    b.ToTable("SafetyItemsReport");
                });

            modelBuilder.Entity("maria.Model.SafetyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projectlocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamLeaderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamLeaderNum")
                        .HasColumnType("int");

                    b.Property<string>("TeamMembers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamNum")
                        .HasColumnType("int");

                    b.Property<string>("TechName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SafetyReport");
                });

            modelBuilder.Entity("maria.Model.SafetyReportImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("safetyReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("safetyReportId");

                    b.ToTable("SafetyReportImage");
                });

            modelBuilder.Entity("maria.Model.Scaffold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ElectricWirelength")
                        .HasColumnType("int");

                    b.Property<int>("FacadeId")
                        .HasColumnType("int");

                    b.Property<string>("HeightBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Liftingلأoods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberTransfers")
                        .HasColumnType("int");

                    b.Property<string>("PowerSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WidthBox")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Wirelength")
                        .HasColumnType("int");

                    b.Property<decimal?>("x")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("y")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacadeId");

                    b.ToTable("Scaffold");
                });

            modelBuilder.Entity("maria.Model.SiteReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projectlocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechSignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SiteReports");
                });

            modelBuilder.Entity("maria.Model.SiteReportImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("siteReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("siteReportId");

                    b.ToTable("SiteReportImages");
                });

            modelBuilder.Entity("maria.Model.CheckingItemReport", b =>
                {
                    b.HasOne("maria.Model.CheckingItem", "checkingItem")
                        .WithMany("checkingItemReport")
                        .HasForeignKey("CheckingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maria.Model.SiteReport", "siteReport")
                        .WithMany("checkingItemReport")
                        .HasForeignKey("SiteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("checkingItem");

                    b.Navigation("siteReport");
                });

            modelBuilder.Entity("maria.Model.DeliveryNoteReport", b =>
                {
                    b.HasOne("maria.Model.DeliveryNote", "deliveryNote")
                        .WithMany("deliveryNoteReport")
                        .HasForeignKey("deliveryNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maria.Model.DeliveryReport", "deliveryReport")
                        .WithMany("checkingItemReport")
                        .HasForeignKey("deliveryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deliveryNote");

                    b.Navigation("deliveryReport");
                });

            modelBuilder.Entity("maria.Model.DelivryReportImage", b =>
                {
                    b.HasOne("maria.Model.DeliveryReport", "deliveryReports")
                        .WithMany()
                        .HasForeignKey("deliveryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deliveryReports");
                });

            modelBuilder.Entity("maria.Model.ElevatorImage", b =>
                {
                    b.HasOne("maria.Model.Elevator", "Elevator")
                        .WithMany("elevatorFiles")
                        .HasForeignKey("ElevatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elevator");
                });

            modelBuilder.Entity("maria.Model.ElevatorInspectionImage", b =>
                {
                    b.HasOne("maria.Model.ElevatorInspectionReport", "ElevatorInspectionReports")
                        .WithMany()
                        .HasForeignKey("ElevatorInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElevatorInspectionReports");
                });

            modelBuilder.Entity("maria.Model.ElevatorInspectionItems", b =>
                {
                    b.HasOne("maria.Model.ElevatorChechingItems", "ElevatorChechingItems")
                        .WithMany("elevatorInspectionItems")
                        .HasForeignKey("CheckingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maria.Model.ElevatorInspectionReport", "elevatorInspectionReport")
                        .WithMany("elevatorInspectionItems")
                        .HasForeignKey("ElevatorInspectionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElevatorChechingItems");

                    b.Navigation("elevatorInspectionReport");
                });

            modelBuilder.Entity("maria.Model.Facade", b =>
                {
                    b.HasOne("maria.Model.LevatorReport", "LevatorReport")
                        .WithMany("facades")
                        .HasForeignKey("LevatorReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevatorReport");
                });

            modelBuilder.Entity("maria.Model.LevatorImage", b =>
                {
                    b.HasOne("maria.Model.LevatorReport", "LevatorReport")
                        .WithMany()
                        .HasForeignKey("LevatorReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevatorReport");
                });

            modelBuilder.Entity("maria.Model.ReportImage", b =>
                {
                    b.HasOne("maria.Model.Report", "Report")
                        .WithMany("ReportFiles")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("maria.Model.SafetyItemsReport", b =>
                {
                    b.HasOne("maria.Model.SafetyItems", "safetyItems")
                        .WithMany("safetyItemsReport")
                        .HasForeignKey("SafetyItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maria.Model.SafetyReport", "safetyReport")
                        .WithMany("safetyItemsReport")
                        .HasForeignKey("SafetyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("safetyItems");

                    b.Navigation("safetyReport");
                });

            modelBuilder.Entity("maria.Model.SafetyReportImage", b =>
                {
                    b.HasOne("maria.Model.SafetyReport", "safetyReport")
                        .WithMany()
                        .HasForeignKey("safetyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("safetyReport");
                });

            modelBuilder.Entity("maria.Model.Scaffold", b =>
                {
                    b.HasOne("maria.Model.Facade", "facade")
                        .WithMany("Scaffolds")
                        .HasForeignKey("FacadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("facade");
                });

            modelBuilder.Entity("maria.Model.SiteReportImage", b =>
                {
                    b.HasOne("maria.Model.SiteReport", "siteReports")
                        .WithMany()
                        .HasForeignKey("siteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("siteReports");
                });

            modelBuilder.Entity("maria.Model.CheckingItem", b =>
                {
                    b.Navigation("checkingItemReport");
                });

            modelBuilder.Entity("maria.Model.DeliveryNote", b =>
                {
                    b.Navigation("deliveryNoteReport");
                });

            modelBuilder.Entity("maria.Model.DeliveryReport", b =>
                {
                    b.Navigation("checkingItemReport");
                });

            modelBuilder.Entity("maria.Model.Elevator", b =>
                {
                    b.Navigation("elevatorFiles");
                });

            modelBuilder.Entity("maria.Model.ElevatorChechingItems", b =>
                {
                    b.Navigation("elevatorInspectionItems");
                });

            modelBuilder.Entity("maria.Model.ElevatorInspectionReport", b =>
                {
                    b.Navigation("elevatorInspectionItems");
                });

            modelBuilder.Entity("maria.Model.Facade", b =>
                {
                    b.Navigation("Scaffolds");
                });

            modelBuilder.Entity("maria.Model.LevatorReport", b =>
                {
                    b.Navigation("facades");
                });

            modelBuilder.Entity("maria.Model.Report", b =>
                {
                    b.Navigation("ReportFiles");
                });

            modelBuilder.Entity("maria.Model.SafetyItems", b =>
                {
                    b.Navigation("safetyItemsReport");
                });

            modelBuilder.Entity("maria.Model.SafetyReport", b =>
                {
                    b.Navigation("safetyItemsReport");
                });

            modelBuilder.Entity("maria.Model.SiteReport", b =>
                {
                    b.Navigation("checkingItemReport");
                });
#pragma warning restore 612, 618
        }
    }
}
